import Variants from 'src/types/variants';

const VALUES = {
  white: 'rgb(var(--white))',
  'white/0': 'rgba(var(--white), 0)',
  'white/5': 'rgba(var(--white), 0.05)',
  'white/10': 'rgba(var(--white), 0.1)',
  'white/20': 'rgba(var(--white), 0.2)',
  'white/30': 'rgba(var(--white), 0.3)',
  'white/40': 'rgba(var(--white), 0.4)',
  'white/50': 'rgba(var(--white), 0.5)',
  'white/60': 'rgba(var(--white), 0.6)',
  'white/70': 'rgba(var(--white), 0.7)',
  'white/80': 'rgba(var(--white), 0.8)',
  'white/90': 'rgba(var(--white), 0.9)',
  'white/100': 'rgba(var(--white), 1)',

  inherit: 'inherit',
  black: 'rgb(var(--black))',
  transparent: 'transparent',
  current: 'current',
  none: 'none',

  'red-10': `rgb(var(--red-10))`,
  'red-20': `rgb(var(--red-20))`,
  'red-30': `rgb(var(--red-30))`,
  'red-40': `rgb(var(--red-40))`,
  'red-50': `rgb(var(--red-50))`,
  'red-60': `rgb(var(--red-60))`,
  'red-70': `rgb(var(--red-70))`,
  'red-80': `rgb(var(--red-80))`,
  'red-90': `rgb(var(--red-90))`,
  'red-95': `rgb(var(--red-95))`,
  'red-100': `rgb(var(--red-100))`,

  'yellow-10': `rgb(var(--yellow-10))`,
  'yellow-20': `rgb(var(--yellow-20))`,
  'yellow-30': `rgb(var(--yellow-30))`,
  'yellow-40': `rgb(var(--yellow-40))`,
  'yellow-50': `rgb(var(--yellow-50))`,
  'yellow-60': `rgb(var(--yellow-60))`,
  'yellow-70': `rgb(var(--yellow-70))`,
  'yellow-80': `rgb(var(--yellow-80))`,
  'yellow-90': `rgb(var(--yellow-90))`,
  'yellow-95': `rgb(var(--yellow-95))`,
  'yellow-100': `rgb(var(--yellow-100))`,

  'orange-10': `rgb(var(--orange-10))`,
  'orange-20': `rgb(var(--orange-20))`,
  'orange-30': `rgb(var(--orange-30))`,
  'orange-40': `rgb(var(--orange-40))`,
  'orange-50': `rgb(var(--orange-50))`,
  'orange-60': `rgb(var(--orange-60))`,
  'orange-70': `rgb(var(--orange-70))`,
  'orange-80': `rgb(var(--orange-80))`,
  'orange-90': `rgb(var(--orange-90))`,
  'orange-95': `rgb(var(--orange-95))`,
  'orange-100': `rgb(var(--orange-100))`,

  'green-10': `rgb(var(--green-10))`,
  'green-20': `rgb(var(--green-20))`,
  'green-30': `rgb(var(--green-30))`,
  'green-40': `rgb(var(--green-40))`,
  'green-50': `rgb(var(--green-50))`,
  'green-60': `rgb(var(--green-60))`,
  'green-70': `rgb(var(--green-70))`,
  'green-80': `rgb(var(--green-80))`,
  'green-90': `rgb(var(--green-90))`,
  'green-95': `rgb(var(--green-95))`,
  'green-100': `rgb(var(--green-100))`,

  'indigo-10': `rgb(var(--indigo-10))`,
  'indigo-20': `rgb(var(--indigo-20))`,
  'indigo-30': `rgb(var(--indigo-30))`,
  'indigo-40': `rgb(var(--indigo-40))`,
  'indigo-50': `rgb(var(--indigo-50))`,
  'indigo-60': `rgb(var(--indigo-60))`,
  'indigo-70': `rgb(var(--indigo-70))`,
  'indigo-80': `rgb(var(--indigo-80))`,
  'indigo-90': `rgb(var(--indigo-90))`,
  'indigo-95': `rgb(var(--indigo-95))`,
  'indigo-100': `rgb(var(--indigo-100))`,

  'gray-10': `rgb(var(--gray-10))`,
  'gray-20': `rgb(var(--gray-20))`,
  'gray-30': `rgb(var(--gray-30))`,
  'gray-40': `rgb(var(--gray-40))`,
  'gray-50': `rgb(var(--gray-50))`,
  'gray-60': `rgb(var(--gray-60))`,
  'gray-70': `rgb(var(--gray-70))`,
  'gray-80': `rgb(var(--gray-80))`,
  'gray-90': `rgb(var(--gray-90))`,
  'gray-95': `rgb(var(--gray-95))`,
  'gray-100': `rgb(var(--gray-100))`,

  'brown-10': `rgb(var(--brown-10))`,
  'brown-20': `rgb(var(--brown-20))`,
  'brown-30': `rgb(var(--brown-30))`,
  'brown-40': `rgb(var(--brown-40))`,
  'brown-50': `rgb(var(--brown-50))`,
  'brown-60': `rgb(var(--brown-60))`,
  'brown-70': `rgb(var(--brown-70))`,
  'brown-80': `rgb(var(--brown-80))`,
  'brown-90': `rgb(var(--brown-90))`,
  'brown-95': `rgb(var(--brown-95))`,
  'brown-100': `rgb(var(--brown-100))`,

  'purple-10': `rgb(var(--purple-10))`,
  'purple-20': `rgb(var(--purple-20))`,
  'purple-30': `rgb(var(--purple-30))`,
  'purple-40': `rgb(var(--purple-40))`,
  'purple-50': `rgb(var(--purple-50))`,
  'purple-60': `rgb(var(--purple-60))`,
  'purple-70': `rgb(var(--purple-70))`,
  'purple-80': `rgb(var(--purple-80))`,
  'purple-90': `rgb(var(--purple-90))`,
  'purple-95': `rgb(var(--purple-95))`,
  'purple-100': `rgb(var(--purple-100))`,

  'cyan-10': `rgb(var(--cyan-10))`,
  'cyan-20': `rgb(var(--cyan-20))`,
  'cyan-30': `rgb(var(--cyan-30))`,
  'cyan-40': `rgb(var(--cyan-40))`,
  'cyan-50': `rgb(var(--cyan-50))`,
  'cyan-60': `rgb(var(--cyan-60))`,
  'cyan-70': `rgb(var(--cyan-70))`,
  'cyan-80': `rgb(var(--cyan-80))`,
  'cyan-90': `rgb(var(--cyan-90))`,
  'cyan-95': `rgb(var(--cyan-95))`,
  'cyan-100': `rgb(var(--cyan-100))`,

  'pink-10': `rgb(var(--pink-10))`,
  'pink-20': `rgb(var(--pink-20))`,
  'pink-30': `rgb(var(--pink-30))`,
  'pink-40': `rgb(var(--pink-40))`,
  'pink-50': `rgb(var(--pink-50))`,
  'pink-60': `rgb(var(--pink-60))`,
  'pink-70': `rgb(var(--pink-70))`,
  'pink-80': `rgb(var(--pink-80))`,
  'pink-90': `rgb(var(--pink-90))`,
  'pink-95': `rgb(var(--pink-95))`,
  'pink-100': `rgb(var(--pink-100))`,
};

const colorProps = {
  color: {
    isResponsive: true,
    properties: ['color'],
    values: VALUES,
  },

  borderColor: {
    isResponsive: true,
    properties: ['borderColor'],
    values: VALUES,
  },

  borderTopColor: {
    properties: ['borderTopColor'],
    values: VALUES,
  },

  borderLeftColor: {
    properties: ['borderLeftColor'],
    values: VALUES,
  },

  borderRightColor: {
    isResponsive: true,
    properties: ['borderRightColor'],
    values: VALUES,
  },

  borderBottomColor: {
    properties: ['borderBottomColor'],
    values: VALUES,
  },

  backgroundColor: {
    isResponsive: true,
    properties: ['backgroundColor'],
    values: VALUES,
  },
} satisfies Variants.VariantMap;

export default colorProps;
