const currencies = [
  {
    name: 'usd',
    symbol: '$',
    country: 'United States of America',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197484.png',
  },
  {
    name: 'aed',
    symbol: 'د.إ',
    country: 'United Arab Emirates',
    image: 'https://cdn-icons-png.flaticon.com/128/323/323301.png',
  },
  {
    name: 'ars',
    symbol: '$',
    country: 'Argentina',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197573.png',
  },
  {
    name: 'aud',
    symbol: '$',
    country: 'Australia',
    image: 'https://cdn-icons-png.flaticon.com/128/323/323367.png',
  },
  {
    name: 'bdt',
    symbol: '৳',
    country: 'Bangladesh',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197509.png',
  },
  {
    name: 'brl',
    symbol: 'R$',
    country: 'Brazil',
    image: 'https://cdn-icons-png.flaticon.com/128/9906/9906449.png',
  },
  {
    name: 'cad',
    symbol: '$',
    country: 'Canada',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197430.png',
  },
  {
    name: 'chf',
    symbol: 'CHF',
    country: 'Switzerland',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197540.png',
  },
  {
    name: 'clp',
    symbol: '$',
    country: 'Chile',
    image: 'https://cdn-icons-png.flaticon.com/128/5921/5921927.png',
  },
  {
    name: 'cny',
    symbol: '¥',
    country: 'China',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197375.png',
  },
  {
    name: 'czk',
    symbol: 'Kč',
    country: 'Czech Republic',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197576.png',
  },
  {
    name: 'dkk',
    symbol: 'kr',
    country: 'Denmark',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197565.png',
  },
  {
    name: 'gbp',
    symbol: '£',
    country: 'United Kingdom',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197565.png',
  },
  {
    name: 'gel',
    symbol: '₾',
    country: 'Georgia',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197380.png',
  },
  {
    name: 'hkd',
    symbol: '$',
    country: 'Hong Kong',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197570.png',
  },
  {
    name: 'huf',
    symbol: 'Ft',
    country: 'Hungary',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197584.png',
  },
  {
    name: 'idr',
    symbol: 'Rp',
    country: 'Indonesia',
    image: 'https://cdn-icons-png.flaticon.com/128/11654/11654463.png',
  },
  {
    name: 'ils',
    symbol: '₪',
    country: 'Israel',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197577.png',
  },
  {
    name: 'inr',
    symbol: '₹',
    country: 'India',
    image: 'https://cdn-icons-png.flaticon.com/128/9906/9906480.png',
  },
  {
    name: 'jpy',
    symbol: '¥',
    country: 'Japan',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197604.png',
  },
  {
    name: 'krw',
    symbol: '₩',
    country: 'South Korea',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197604.png',
  },
  {
    name: 'kwd',
    symbol: 'د.ك',
    country: 'Kuwait',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197459.png',
  },
  {
    name: 'mxn',
    symbol: '$',
    country: 'Mexico',
    image: 'https://cdn-icons-png.flaticon.com/128/5372/5372848.png',
  },
  {
    name: 'myr',
    symbol: 'RM',
    country: 'Malaysia',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197581.png',
  },
  {
    name: 'ngn',
    symbol: '₦',
    country: 'Nigeria',
    image: 'https://cdn-icons-png.flaticon.com/128/5922/5922004.png',
  },
  {
    name: 'nok',
    symbol: 'kr',
    country: 'Norway',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197579.png',
  },
  {
    name: 'nzd',
    symbol: '$',
    country: 'New Zealand',
    image: 'https://cdn-icons-png.flaticon.com/128/12360/12360728.png',
  },
  {
    name: 'php',
    symbol: '₱',
    country: 'Philippines',
    image: 'https://cdn-icons-png.flaticon.com/128/12364/12364272.png',
  },
  {
    name: 'pkr',
    symbol: '₨',
    country: 'Pakistan',
    image: 'https://cdn-icons-png.flaticon.com/128/323/323352.png',
  },
  {
    name: 'pln',
    symbol: 'zł',
    country: 'Poland',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197529.png',
  },
  {
    name: 'rub',
    symbol: '₽',
    country: 'Russia',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197529.png',
  },
  {
    name: 'sar',
    symbol: '﷼',
    country: 'Saudi Arabia',
    image: 'https://cdn-icons-png.flaticon.com/128/5111/5111777.png',
  },
  {
    name: 'sek',
    symbol: 'kr',
    country: 'Sweden',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197564.png',
  },
  {
    name: 'sgd',
    symbol: '$',
    country: 'Singapore',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197496.png',
  },
  {
    name: 'thb',
    symbol: '฿',
    country: 'Thailand',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197452.png',
  },
  {
    name: 'try',
    symbol: '₺',
    country: 'Turkey',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197518.png',
  },
  {
    name: 'twd',
    symbol: 'NT$',
    country: 'Taiwan',
    image: 'https://cdn-icons-png.flaticon.com/128/5373/5373308.png',
  },
  {
    name: 'uah',
    symbol: '₴',
    country: 'Ukraine',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197572.png',
  },
  {
    name: 'vef',
    symbol: 'Bs',
    country: 'Venezuela',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197580.png',
  },
  {
    name: 'vnd',
    symbol: '₫',
    country: 'Vietnam',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197473.png',
  },
  {
    name: 'zar',
    symbol: 'R',
    country: 'South Africa',
    image: 'https://cdn-icons-png.flaticon.com/128/197/197562.png',
  },
] as const;

export default currencies;
